#! /bin/bash

CONTAINER_NAME="suvitruf-grafana-dashboard"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	rm -fr ./logs/*
fi

hname(){
    hostname -s
}

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 80:80 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 -p 2004:2004 -p 81:81 -e HOST_NAME_SHORT=$(hname) --name $CONTAINER_NAME suvitruf/grafana_graphite
